apiVersion: v1
kind: Service
metadata:
  name: maven-app-service
  labels:
    app: maven-app-app
spec:
  type: LoadBalancer
  selector:
    app: maven-app-app
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080          
